Navbar
SunStratos/Website pull request #8
Opened 2022-12-14 17:55 UTC by SMALLASIAN

2022-12-14 17:57 UTC, SMALLASIAN commented
<img width="1081" alt="Screenshot 2022-12-14 at 17 54 31" src="https://user-images.githubusercontent.com/103758881/207671207-112a8b4d-0cce-4432-b05c-622f6d26f99b.png">
<img width="376" alt="Screenshot 2022-12-14 at 17 54 45" src="https://user-images.githubusercontent.com/103758881/207671212-69e2ef09-5a97-441c-ae11-797fdb9fcbb4.png">

2023-01-28 17:11 UTC, SMALLASIAN commented
<img width="1392" alt="Screenshot 2023-01-28 at 17 10 22" src="https://user-images.githubusercontent.com/103758881/215279652-720564d4-0b2d-4cb3-949b-1897856a95b6.png">
<img width="846" alt="Screenshot 2023-01-28 at 17 10 37" src="https://user-images.githubusercontent.com/103758881/215279653-f07e1d0a-d677-4d0a-be62-b1bc30510cd2.png">
<img width="827" alt="Screenshot 2023-01-28 at 17 11 00" src="https://user-images.githubusercontent.com/103758881/215279655-9c768a2d-f1e8-4313-be9d-cc5adcb696d1.png">

2023-01-28 17:12 UTC, SMALLASIAN commented
<img width="872" alt="Screenshot 2023-01-28 at 17 11 55" src="https://user-images.githubusercontent.com/103758881/215279700-250ff022-f71c-46f4-8b99-06c897f104e1.png">

2023-01-29 22:27 UTC, awiktorowicz requested changes

2023-01-29 22:27 UTC, awiktorowicz commented on app/views/navbar/_navbar.html.erb
> +  <script>
JavaScript and Style should not be defined in a View. You could include it in the view by adding a similar script `<%= javascript_include_tag "[Name_of_the_js_file]" %>` .  This way, the script will only be loaded when the view is rendered and not on every page. It is also a good practice to minify and compress the javascript files for the production environment.

2023-01-29 22:37 UTC, awiktorowicz requested changes

2023-01-29 22:37 UTC, awiktorowicz commented on app/helpers/team_helper.rb
> +module TeamHelper
Do we need it?

2023-01-29 22:37 UTC, awiktorowicz commented on app/helpers/recruitment_helper.rb
> +module RecruitmentHelper
Same as above

2023-01-29 22:37 UTC, awiktorowicz commented on app/helpers/project_helper.rb
> +module ProjectHelper
Same as above

2023-01-29 22:37 UTC, awiktorowicz commented on app/helpers/idea_helper.rb
> +module IdeaHelper
Same as above

2023-01-29 22:37 UTC, awiktorowicz commented on app/helpers/home_helper.rb
> +module HomeHelper
Same as above

2023-01-29 22:37 UTC, awiktorowicz commented on app/helpers/contact_helper.rb
> +module ContactHelper
Same as above

2023-01-29 22:37 UTC, awiktorowicz commented on app/helpers/achievement_helper.rb
> +module AchievementHelper
Same as above

2023-02-04 12:31 UTC, merged